### ISSUE TITLE
Problem with Source_T2 subroutine 

### ISSUE THREAD

**Issue by mhadziabdic** [DelNov/T-Flows#128] opened 2019-03-12 15:52 UTC
It is very strange problem. I am solving large domain with inflow and outflow. Inflow is read from the file. If I run computation with heat transfer variables that are solved after T2 equation, zeta and F22 are getting very strange random large numbers. If I just move T2 equation after these two equations in Main_pro.f90 like this
      if(turbulence_model .eq. K_EPS_ZETA_F .or. &
         turbulence_model .eq. HYBRID_LES_RANS) then
        call Calculate_Shear_And_Vorticity(flow)

        call Compute_Turbulent(flow, sol, dt, ini, kin, n)
        call Compute_Turbulent(flow, sol, dt, ini, eps, n)

        call Update_Boundary_Values(flow)

        call Compute_F22(grid, sol, ini, f22)
        call Compute_Turbulent(flow, sol, dt, ini, zeta, n)

        call Calculate_Vis_T_K_Eps_Zeta_F(flow)

        if(heat_transfer) then
          call Calculate_Heat_Flux(flow)
          call Compute_Turbulent(flow, sol, dt, ini, t2,  n)
        end if

      end if

problem is gone. It seems like Source_T2 is doing something with coefficient matrix a and b, that somehow enter zeta and F22 equations. Any idea?

**Comment by palkinev** [comment] 2019-03-18 10:59
I found out that this issue is caused by **HYBRID_LES_RANS** + **heat_transfer** combination.
It is fixed by pull request #130 .

**Comment by palkinev** [comment] 2019-03-20 10:07
I think this issue can be closed now.

**Closed** 2019-04-13 07:06 UTC
